markdown: kramdown
highlighter: rouge
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"


all_categories: [
["web", "Web","/posts/web.html"], 
["python", "Python","/posts/python.html"],
["reading", "读书笔记","/posts/reading.html"], 
["tools", "工具","/posts/tools.html"],
["other", "杂记","/posts/other.html"],
["portfolio", "作品展示","frankwong1008.github.io"],
["about", "关于","/about.html"],
]

paginate: 8
paginate_path: "posts/page:num"
timezone: #

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
